name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: wmsy
          POSTGRES_PASSWORD: group15
          POSTGRES_DB: wmsy
        options: >-
          --health-cmd "pg_isready -U postgres -d test_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to latest version

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: backend

      - name: Wait for PostgreSQL
        run: |
          until pg_isready --host=localhost --port=5432 -U postgres; do 
            echo "Waiting for PostgreSQL to be ready...";
            sleep 1; 
          done

      - name: Verify PostgreSQL connection
        run: |
          PGPASSWORD=postgres psql -h localhost -U postgres -d test_db -c '\l'

      - name: Set up environment variables
        run: |
          echo DB_HOST=localhost >> $GITHUB_ENV
          echo DB_USER=postgres >> $GITHUB_ENV
          echo DB_PASS=postgres >> $GITHUB_ENV
          echo DB_NAME=test_db >> $GITHUB_ENV
          echo NODE_ENV=test >> $GITHUB_ENV

      - name: Run tests
        run: npm test
        working-directory: backend

      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend

      - name: Deploy to Render (Backend)
        if: github.ref == 'refs/heads/main'
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST \
            -H 'Authorization: Bearer $RENDER_API_KEY' \
            -H 'Content-Type: application/json' \
            -d '{"serviceId": "srv-cpnvchmehbks738egqf0"}' \
            https://api.render.com/v1/services/srv-cpnvchmehbks738egqf0/deploys

      - name: Deploy to Render (Frontend)
        if: github.ref == 'refs/heads/main'
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST \
            -H 'Authorization: Bearer $RENDER_API_KEY' \
            -H 'Content-Type: application/json' \
            -d '{"serviceId": "srv-cpo000lds78s73b7o6hg"}' \
            https://api.render.com/v1/services/srv-cpo000lds78s73b7o6hg/deploys
