name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASS }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: backend

      - name: Wait for PostgreSQL
        run: until pg_isready --host=localhost --port=5432; do echo waiting for postgres; sleep 1; done

      - name: Set up environment variables
        run: |
          echo DB_HOST=localhost >> $GITHUB_ENV
          echo DB_USER=${{ secrets.DB_USER }} >> $GITHUB_ENV
          echo DB_PASS=${{ secrets.DB_PASS }} >> $GITHUB_ENV
          echo DB_NAME=${{ secrets.DB_NAME }} >> $GITHUB_ENV
          echo NODE_ENV=test >> $GITHUB_ENV

      - name: Run tests
        run: npm test
        working-directory: backend

      - name: Build frontend
        run: npm install
        working-directory: frontend

      - name: Deploy to Render
        if: github.ref == 'refs/heads/main'
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST \
            -H 'Authorization: Bearer $RENDER_API_KEY' \
            -H 'Content-Type: application/json' \
            -d '{"serviceId": "your-backend-service-id"}' \
            https://api.render.com/v1/services/your-backend-service-id/deploys

          curl -X POST \
            -H 'Authorization: Bearer $RENDER_API_KEY' \
            -H 'Content-Type: application/json' \
            -d '{"serviceId": "your-frontend-service-id"}' \
            https://api.render.com/v1/services/your-frontend-service-id/deploys
