name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASS }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        options: >-
          --health-cmd "pg_isready -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_NAME }}"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: backend

      - name: Wait for PostgreSQL
        run: |
          until pg_isready --host=localhost --port=5432 -U ${{ secrets.DB_USER }}; do 
            echo "Waiting for PostgreSQL to be ready...";
            sleep 1; 
          done

      - name: Verify PostgreSQL connection
        run: |
          PGPASSWORD=${{ secrets.DB_PASS }} psql -h localhost -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_NAME }} -c '\l'

      - name: Set up environment variables
        run: |
          echo DB_HOST=localhost >> $GITHUB_ENV
          echo DB_USER=${{ secrets.DB_USER }} >> $GITHUB_ENV
          echo DB_PASS=${{ secrets.DB_PASS }} >> $GITHUB_ENV
          echo DB_NAME=${{ secrets.DB_NAME }} >> $GITHUB_ENV
          echo NODE_ENV=test >> $GITHUB_ENV

      - name: Run tests
        run: npm test
        working-directory: backend

      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend

      - name: Deploy to Render (Backend)
        if: github.ref == 'refs/heads/main'
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST \
            -H 'Authorization: Bearer $RENDER_API_KEY' \
            -H 'Content-Type: application/json' \
            -d '{"serviceId": "srv-cpnvchmehbks738egqf0"}' \
            https://api.render.com/v1/services/srv-cpnvchmehbks738egqf0/deploys

      - name: Deploy to Render (Frontend)
        if: github.ref == 'refs/heads/main'
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST \
            -H 'Authorization: Bearer $RENDER_API_KEY' \
            -H 'Content-Type: application/json' \
            -d '{"serviceId": "srv-cpo000lds78s73b7o6hg"}' \
            https://api.render.com/v1/services/srv-cpo000lds78s73b7o6hg/deploys
